name: "Future Amplify Deploy"

# Note that I will have to change the way my code is deployed for it this to matter, future edition


on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    name: test a
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm cli
      - run: npm test

