name: "Future Amplify Deploy"

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    name: test a
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm cli
      - run: npm test

